### PR TITLE
Disable http download

### LINKED ISSUE #576: Disable public access to the download folder
The public access point "https://ezid.cdlib.org/download/" is not needed anymore as we use the S3 bucket for batch download now. The access point is mapped to the "/apps/ezid/var/www/download/public" folder on the server. We still need the "/apps/ezid/var/www/download/public" folder for other operation. But we don't need to provide public access over URL.

### PR DESCRIPTION
**Pull request by ashleygould**
removes alias download config from apache configs.  drops symlink `~/download`.  Resolves #576

### CODE REVIEW

**Comment by jsjiang** [comment]
@ashleygould Changes look good to me. Should it be merged into the develop branch first then to the main?

Jing

**Comment by ashleygould** [comment]
I don't know your standard practice, but that sounds correct.  I do think we need to run integration tests before deploying to prod.

________________________________________

**Comment by jsjiang** [comment]
I will deploy tag 3.2.9rc0 on ezid-stg and run integration tests tomorrow morning.

**Comment by ashleygould** [comment]
I reverted change to download symlink.  new tag 3.2.9rc1

**Comment by jsjiang** [comment]
Tested tag 3.2.9rc1 on ezid-stg.

**Pull request merged**
